<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWcxnqz2\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWcxnqz2/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWcxnqz2.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWcxnqz2\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWcxnqz2\appDevDebugProjectContainer([
    'container.build_hash' => 'Wcxnqz2',
    'container.build_id' => '129cf758',
    'container.build_time' => 1568196289,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWcxnqz2');
